AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Work in progress attempt for using jersey to expose GEO Label API with AWS Lambda

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  GeolabelFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.n52.geolabel.server.lambda.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/glbservice.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  GeolabelApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/ping'
    Export:
      Name: GlbApi
